---
model_save_path: ""      # model save path
preprocess:
  flag: true                                                     # true: preprocess, false: not preprocess
wandb:
  flag: false
  project_name: DeepPhys
  entity: paperchae

fit:
  model: DeepPhys
  type: DIFF
  time_length: 180
  overlap_interval: 0 # default 0
  img_size: 72
  train_flag: True
  eval_flag: True
  eval_interval: 100
  debug_flag: False                        # True: debug mode (load small dataset, False: normal mode

  train:
    dataset: UBFC
    shuffle: True
    fs: 30 #video fps
    batch_size: 4
    learning_rate: 0.009
    epochs: 30
    loss: MSE
    optimizer: AdamW
    meta:
      flag: false
      inner_optim: adam
      inner_loss: MSE
      inner_lr: 0.01

  test:
    cal_type: FFT
    metric: [ 'MAE','RMSE','MAPE','Pearson' ]
    eval_time_length: 30 # second
    dataset: UBFC
    shuffle: False
    fs: 30 #video fps
    batch_size: 10
