---
model_save_path: "/ssd/ssd0/models/rppg/"      # model save path
preprocess:
  flag: false                              # true: preprocess, false: not preprocess
wandb:
  flag: false
  project_name: rppg
  entity: daeyeolkim

fit:
  model: EfficientPhys                    # DeepPhys, TSCAN, EfficientPhys, BigSmall, PhysNet, PhysFormer, APNET
  type: DIFF
  time_length: 360
  overlap_interval: 0 # default 0
  img_size: 72
  train_flag: False
  eval_flag: True
  eval_interval: 100
  debug_flag: True                        # True: debug mode (load small dataset, False: normal mode)
  model_save_flag: False                   # True: save model, False: not save model

  train:
    dataset: UBFC
    shuffle: True
    fs: 30 #video fps
    batch_size: 8
    learning_rate: 0.009
    epochs: 15
    loss: MSE
    optimizer: AdamW
    meta:
      flag: false
      inner_optim: adam
      inner_loss: MSE
      inner_lr: 0.01

  test:
    dataset: UBFC
    shuffle: False
    fs: 30 #video fps
    batch_size: 8
    cal_type: FFT
    metric: [ 'MAE','RMSE','MAPE','Pearson' ]
    eval_time_length: 5 # second

