---
model_save_path: ""      # model save path
preprocess:
  flag: false                                                     # true: preprocess, false: not preprocess

fit:
  model: PhysNet
  type: CONT
  time_length: 64
  overlap_interval: 0 # default 0
  img_size: 96
  train_flag: True
  eval_flag: True
  eval_interval: 100
  debug_flag: True                        # True: debug mode (load small dataset, False: normal mode

  train:
    dataset: UBFC
    shuffle: True
    fs: 30 #video fps
    batch_size: 16
    learning_rate: 0.001
    epochs: 30
    loss: neg_pearson
    optimizer: Adam
    meta:
      flag: false
      inner_optim: adam
      inner_loss: MSE
      inner_lr: 0.01

  test:
    cal_type: FFT
    metric: [ 'MAE','RMSE','MAPE','Pearson' ]
    eval_time_length: 30 # second
    dataset: UBFC
    shuffle: False
    fs: 30 #video fps
    batch_size: 16

