---
data_root_path : "/home/jh/ext_hdd4000/data/"
dataset_path: "/home/jh/dataset/" # preprocessed data label_path
model_path: "/home/jh/"
preprocess:
  flag: false
  analyze : false
  chunk_size: 4
  datasets:
fit:
  model: EfficientPhys
  time_length: 1
  overlap_interval: 0 # default 0
  img_size: 72
  train_flag: True
  eval_flag: True
  eval_interval: 100
  batch_size: 40
  meta:
    flag: false
    inner_optim: adam
    inner_loss: mse
    inner_lr: 0.01
  train:
    dataset: PURE
    shuffle: false
    fs: 30 #video fps
    batch_size: 40
    learning_rate: 0.009 # 0.001
    epochs: 30
    loss: MSE
    optimizer: AdamW
  test:
    cal_type : FFT
    metric: ['MAE','RMSE','MAPE','Pearson']
    dataset: PURE
    shuffle: false
    fs: 30 #video fps
    batch_size: 40


