---
data_root_path : "/"
dataset_path: "/home/najy/rppg_datasets/" # preprocessed data path
model_path: "/home/najy/rppg/model/"
preprocess:
  flag: false
  analyze : false
  chunk_size: 4
  datasets:
fit:
  model: PhysFormer
  time_length: 64
  overlap_interval: 0 # default 0
  img_size: 128
  train_flag: True
  eval_flag: True
  eval_interval: 100
  batch_size: 10
  meta:
    flag: false
    inner_optim: adam
    inner_loss: mse
    inner_lr: 0.01
  train:
    dataset: UBFC
    shuffle: true
    fs: 30 #video fps
    batch_size: 10
    learning_rate: 0.001
    epochs: 100
    loss: neg_pearson
    optimizer: AdamW
  test:
    cal_type : FFT
    metric: ['MAE','RMSE','MAPE','Pearson']
    dataset: PURE
    shuffle: false
    fs: 30 #video fps
    batch_size: 4


