---
data_root_path : "/media/hdd1/"
dataset_path: "/media/hdd1/dy/dataset/" # preprocessed data path
model_path: "/media/hdd1/dy/model/"
preprocess:
  flag: false
  analyze : false
  datasets:
fit:
  flag: true
  model: PhysNet
  train:
    flag: true
    dataset: UBFC
    shuffle: true
    fs: 30 #video fps
    batch_size: 64
    learning_rate: 1e-3
    epochs: 100
    loss: negPearson
    optimizer: adam
  val:
    flag: true
    dataset: UBFC
    shuffle: true
    interval: 1 # min 1
    fs: 30 #video fps
    batch_size: 100
  test:
    flag: true
    metric: ['MAE','RMSE','MAPE','Pearson']
    dataset: UBFC
    shuffle: false
    interval: 20 # test interval epoch
    fs: 30 #video fps
    batch_size: 100


