---
data_root_path : "/hdd/hdd1/dataset/data/"
dataset_path: "/hdd/hdd1/dataset/data/preprocessed" # preprocessed data path
model_path: "/hdd/hdd1/models/rppg/deepphys_ubfc_pure/"
preprocess:
  flag: False
  analyze : false
  chunk_size: 4
  datasets:
fit:
  model: DeepPhys
  time_length: 1
  overlap_interval: 0 # default 0
  img_size: 72
  train_flag: True
  eval_flag: True
  eval_interval: 100
  batch_size: 720
  meta:
    flag: false
    inner_optim: adam
    inner_loss: MSE
    inner_lr: 0.01
  train:
    dataset: UBFC
    shuffle: true
    fs: 30 #video fps
    batch_size: 720
    learning_rate: 0.009
    epochs: 30
    loss: MSE
    optimizer: AdamW
  test:
    cal_type : FFT
    metric: ['MAE','RMSE','MAPE','Pearson']
    dataset: PURE
    shuffle: false
    fs: 30 #video fps
    batch_size: 300


