---
preprocess:
  flag: false
  analyze : false
  dataset_path:
  save_path:
  datasets:
fit:
  flag: true
  model: PhysNet
  train:
    flag: true
    dataset: UBFC
    fs: 30 #video fps
    batch_size: 64
    learning_rate: 1e-3
    epochs: 100
    loss: negPearson
    optimizer: adam
  val:
    flag: true
    dataset: UBFC
    interval: 1 # min 1
    fs: 30 #video fps
    batch_size: 100
  test:
    flag: true
    metric: ['MAE','RMSE','MAPE','Pearson']
    dataset: UBFC
    interval: 20 # test interval epoch
    fs: 30 #video fps
    batch_size: 100


