---
models:
- CHROM:
        model: CHROM
        type: CONT
        preprocess_type: CONT
        img_size: 128
        time_length: 48
        batch_size: 100
        optimizer: AdamW
        loss: neg_pearson
        learning_rate: 0.001
- GREEN: # done
      model: GREEN
      type: CONT
      preprocess_type: CONT
      img_size: 128
      time_length: 300
      batch_size: 4
      optimizer: AdamW
      loss: neg_pearson
      learning_rate: 0.001
- POS: # done
      model: POS
      type: CONT
      preprocess_type: CONT
      img_size: 128
      time_length: 300
      batch_size: 100
      optimizer: AdamW
      loss: neg_pearson
      learning_rate: 0.001
- LGI: # done
      model: LGI
      type: CONT
      preprocess_type: CONT
      img_size: 128
      time_length: 300
      batch_size: 4
      optimizer: AdamW
      loss: neg_pearson
      learning_rate: 0.001
- PCA:
      model: PCA
      type: CONT
      preprocess_type: CONT
      img_size: 128
      time_length: 300
      batch_size: 4
      optimizer: AdamW
      loss: neg_pearson
      learning_rate: 0.001

- SSR:
      model: SSR
      type: CONT
      preprocess_type: CONT
      img_size: 128
      time_length: 300
      batch_size: 4
      optimizer: AdamW
      loss: neg_pearson
      learning_rate: 0.001
#- ICA:
#      model: ICA
#      type: CONT
#      preprocess_type: CONT
#      img_size: 128
#      time_length: 300
#      batch_size: 4
#      optimizer: AdamW
#      loss: neg_pearson
#      learning_rate: 0.001


#- DeepPhys:
#    model: DeepPhys
#    type: DIFF
#    preprocess_type: DIFF
#    img_size: 72
#    time_length: 180
#    batch_size: 4
#    optimizer: AdamW
#    loss: MSE
#    learning_rate: 0.009
#    eval_time_length: 10
#    epochs:
#        ubfc: 15
#        pure: 10
##
#
#- EfficientPhys:
#    model: EfficientPhys
#    type: DIFF
#    preprocess_type: CONT
#    img_size: 72
#    time_length: 10
#    batch_size: 72
#    optimizer: AdamW
#    loss: MSE
#    learning_rate: 0.009
#    eval_time_length: 10
#    epochs:
#      ubfc: 15
#      pure: 10

#- BigSmall:
#    model: BigSmall
#    type: DIFF
#    preprocess_type: DIFF
#    img_size: 144
#    time_length: 3
#    batch_size: 240
#    optimizer: AdamW
#    loss: MSE
#    learning_rate: 1e-3
#    eval_time_length: 10
#    epochs:
#      ubfc: 13
#      pure: 10

#- PhysNet:
#    model: PhysNet
#    type: CONT
#    preprocess_type: CONT
#    img_size: 128
#    time_length: 128
#    batch_size: 8
#    optimizer: Adam
#    loss: neg_pearson
#    learning_rate: 0.0001
#    scheduler: None
#    eval_time_length: 10
#    epochs:
#      ubfc: 15
#      pure: 15

#- PhysFormer:
#      model: PhysFormer
#      type: CONT
#      preprocess_type: CONT
#      img_size: 128
#      time_length: 160
#      batch_size: 4
#      optimizer: Adam
#      loss: CLGDLoss
#      learning_rate: 0.0001


